# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch

from flag_gems.ops.attention import flash_attention_forward

logger = logging.getLogger(__name__)


def _flash_attention_forward_no_dropout_inplace(
    query,
    key,
    value,
    cum_seq_q,
    cum_seq_k,
    max_q,
    max_k,
    is_causal,
    return_debug_mask,
    *,
    scale=None,
    window_size_left=None,
    window_size_right=None,
    seqused_k=None,
    alibi_slopes=None,
):
    """FlagGems implementation of ``aten::_flash_attention_forward_no_dropout_inplace``.

    This is a specialised variant of ``_flash_attention_forward`` that drops the
    ``dropout_p`` argument (it is implicitly ``0.0``) and writes the attention
    output in-place into ``query``. The heavy lifting is delegated to the
    existing Triton FlashAttention kernel (:func:`flash_attention_forward`),
    which runs the ``mha_fwd`` Triton kernel.

    Args:
        query: ``(batch, num_heads, seq_len_q, head_dim)``.
        key:   ``(batch, num_kv_heads, seq_len_kv, head_dim)``.
        value: ``(batch, num_kv_heads, seq_len_kv, head_dim)``.
        cum_seq_q / cum_seq_k: optional cumulative sequence lengths (varlen).
        max_q / max_k: maximum sequence lengths.
        is_causal: whether to apply causal masking.
        return_debug_mask: whether to return the debug attention mask.
        scale: optional scale factor for the QK dot product.
        window_size_left / window_size_right: sliding-window attention sizes.
        seqused_k: optional per-batch key sequence lengths.
        alibi_slopes: optional ALiBi bias slopes.

    Returns:
        ``(output, softmax_logsumexp, rng_state, unused, debug_attn_mask)``.
        ``output`` aliases ``query`` (written in-place).
    """
    logger.debug("GEMS FLASH_ATTENTION_FORWARD_NO_DROPOUT_INPLACE")

    # FlashAttention only supports fp16/bf16 inputs.
    assert query.dtype in (
        torch.float16,
        torch.bfloat16,
    ), f"expected fp16/bf16 query, got {query.dtype}"

    # No dropout for this variant.
    dropout_p = 0.0

    # Run the existing Triton FlashAttention forward kernel.
    #
    # ``disable_splitkv`` is set because the split-KV combine kernel of the
    # shared ``mha_fwd`` path can leave output rows unwritten for some shapes,
    # which would violate the in-place contract (the query must hold the full
    # result). The non-split kernel path is numerically exact for the shapes
    # exercised by this operator.
    out, lse, philox_seed, philox_offset, debug_attn_mask = flash_attention_forward(
        query,
        key,
        value,
        cum_seq_q,
        cum_seq_k,
        max_q,
        max_k,
        dropout_p,
        is_causal,
        return_debug_mask,
        scale=scale,
        window_size_left=window_size_left,
        window_size_right=window_size_right,
        seqused_k=seqused_k,
        alibi_slopes=alibi_slopes,
        disable_splitkv=True,
    )

    # In-place semantics: the result is written back into ``query``.
    query.copy_(out)
    return query, lse, philox_seed, philox_offset, debug_attn_mask
