# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _nested_from_padded_remove_padding_kernel(
    padded,
    values,
    lengths,
    row_offsets,
    INNER_NUMEL: tl.constexpr,
    L: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """Compacts a padded dense tensor into a flat buffer by removing the padding.

    Each program handles one batch element and copies the leading
    ``length * INNER_NUMEL`` contiguous elements of its row (which hold the real,
    non-padded values) into the destination buffer starting at
    ``row_offsets[pid] * INNER_NUMEL``.
    """
    pid = tle.program_id(axis=0)
    length = tl.load(lengths + pid)
    numel = length * INNER_NUMEL
    dst = tl.load(row_offsets + pid) * INNER_NUMEL
    src = pid * L * INNER_NUMEL
    for start in tl.range(0, numel, BLOCK_SIZE):
        offs = start + tl.arange(0, BLOCK_SIZE)
        mask = offs < numel
        v = tl.load(padded + src + offs, mask=mask)
        tl.store(values + dst + offs, v, mask=mask)


def _nested_from_padded(padded, cpu_nested_shape_example, fuse_transform_0213=False):
    """Create a nested tensor from a padded dense tensor.

    ``cpu_nested_shape_example`` is an int64 tensor on CPU whose i-th row is the
    nested size ``[len_i, *inner_dims]`` of the i-th component. The returned nested
    tensor reuses the values of ``padded`` with the padding rows removed.
    """
    logger.debug("GEMS _NESTED_FROM_PADDED")

    if fuse_transform_0213:
        # (B, L, S, D) -> (B, S, L * D)
        padded = (
            padded.permute(0, 2, 1, 3)
            .contiguous()
            .view(padded.size(0), padded.size(2), padded.size(1) * padded.size(3))
        )

    padded = padded.contiguous()
    sizes = cpu_nested_shape_example.to(torch.int64)
    batch_size = padded.size(0)
    L = padded.size(1)
    inner_dims = list(padded.shape[2:])
    rank = 1 + len(inner_dims)

    inner_numel = 1
    for d in inner_dims:
        inner_numel *= d

    # Compute all small metadata on CPU (cheap, and not intercepted by FlagGems)
    # so only a couple of tiny H2D copies touch the device.
    lengths = sizes[:, 0]
    component_numel = lengths * inner_numel  # numel of each packed component
    total_len = int(lengths.sum().item())
    total = total_len * inner_numel
    # Row offsets (jagged) with a leading zero.
    row_offsets = torch.cat(
        [torch.zeros(1, dtype=torch.int64), torch.cumsum(lengths, dim=0)]
    )

    values = torch.empty(total, dtype=padded.dtype, device=padded.device)

    lengths_dev = lengths.to(padded.device)
    row_offsets_dev = row_offsets.to(padded.device)

    grid = lambda meta: (batch_size,)
    _nested_from_padded_remove_padding_kernel[grid](
        padded,
        values,
        lengths_dev,
        row_offsets_dev,
        INNER_NUMEL=inner_numel,
        L=L,
        # 1024 threads = 32 full warps; saturates memory bandwidth for this
        # elementwise un-padding copy, so a fixed block beats autotune overhead.
        BLOCK_SIZE=1024,
    )

    values = values.view(total_len, *inner_dims)

    # Reconstruct a legacy (``torch.strided`` layout) NestedTensor directly from
    # the packed values, matching the reference aten implementation. Component
    # ``b`` is the contiguous ``[len_i, *inner_dims]`` slice of ``values`` whose
    # storage offset is the cumulative component numel. ``_nested_view_from_buffer``
    # requires a flat 1D buffer, so view the packed values back to 1D; the
    # component shapes are recovered via ``nested_size``/``nested_strides``.
    nested_strides = torch.empty_like(sizes)
    running = torch.ones(batch_size, dtype=torch.int64)
    for d in range(rank - 1, -1, -1):
        nested_strides[:, d] = running
        running = running * sizes[:, d]

    storage_offsets = torch.zeros(batch_size, dtype=torch.int64)
    if batch_size > 1:
        storage_offsets[1:] = torch.cumsum(component_numel[:-1], dim=0)

    return torch.ops.aten._nested_view_from_buffer.default(
        values.view(-1), sizes, nested_strides, storage_offsets
    )


__all__ = ["_nested_from_padded"]
